"use client";

import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { StatusProvider } from "~/context/statusContext";
import { UserProvider, useUserContext } from "~/context/userContext";
import { Toaster } from "sonner";
import { useEffect } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { handleLogout } = useUserContext();

  useEffect(() => {
    window.addEventListener("storage", () => {
      if (!localStorage.token) handleLogout();
    });
  }, []);

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <StatusProvider>
          <UserProvider>{children}</UserProvider>
          <Toaster position="top-right" expand={false} />
        </StatusProvider>
      </body>
    </html>
  );
}
